### ISSUE TITLE
Unrecognized function or variable 'Loc2Glo' and 'SkewFun.'

### ISSUE THREAD

**Issue by chenpengxin** [DrGabor/MiNoM#2]
Seems like the code is incomplete. You didn't provide the definition of multiple functions, such as Loc2Glo() and SkewFun()

**Comment by DrGabor** [comment]
Hi,&nbsp;


The missing functions are in the LiDAR repository.


Best regards,



---Original---

**Comment by chenpengxin** [comment]
> Hi,&nbsp; The missing functions are in the LiDAR repository. Best regards,
> […](#)
> ---Original--- From: "chenpengxin"<notifications@github.com&gt; Date: Sat, Aug 29, 2020 15:46 PM To: "DrGabor/MiNoM"<MiNoM@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: [DrGabor/MiNoM] Unrecognized function or variable 'Loc2Glo' and 'SkewFun.' (#2) Seems like the code is incomplete. You didn't provide the definition of multiple functions, such as Loc2Glo() and SkewFun() — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


That works! 

Cheers!
